FROM postgres:16-alpine

RUN apk add --no-cache \
    aws-cli \
    bash

COPY db-sync.sh /usr/local/bin/db-sync.sh
RUN chmod +x /usr/local/bin/db-sync.sh

ENTRYPOINT ["bash", "/usr/local/bin/db-sync.sh"]
